<?php

function arche_core_gui_page_attachments(array &$page) {
    $languageManager = \Drupal::languageManager();
    // Get the current language object
    $currentLanguage = $languageManager->getCurrentLanguage();
    $page['#attached']['drupalSettings']['arche_core_gui']['gui_lang'] = $currentLanguage->getId();
    $page['#attached']['drupalSettings']['arche_core_gui']['smartsearch_timeout'] = getSmartSearchTimeout();
    $page['#attached']['drupalSettings']['arche_core_gui']['users']['id'] = \Drupal::currentUser()->id();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $page['#attached']['drupalSettings']['arche_core_gui']['users']['name'] = $account->getAccountName();
    $roles = array();
    $roles = \Drupal::currentUser()->getRoles();
    if(count($roles) > 0){ $roles = implode(",", $roles); }
    $page['#attached']['drupalSettings']['arche_core_gui']['users']['roles'] = $roles;
    $attachments['#attached']['library'][] = 'custom_jquery/metadata-class';
}

function getSmartSearchTimeout() {
    $config = \acdhOeaw\arche\lib\Config::fromYaml(\Drupal::service('extension.list.module')->getPath('arche_core_gui') . '/config/config.yaml');
    if(isset($config->smartSearch->searchTimeout)) {
        return (int)$config->smartSearch->searchTimeout;
    }
    return 60000;
}

/*
 * Create a hook for the admin form page to we can use an external javascript file
 * 
 */
function arche_core_gui_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
 
    //form and user permission settings for the collection download views
    $form['#attached']['library'][] = 'arche_core_gui/repo-collection-dl';
    
    $form['#attached']['drupalSettings']['arche_core_gui']['users']['id'] = \Drupal::currentUser()->id();
    $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $form['#attached']['drupalSettings']['arche_core_gui']['users']['name'] = $account->getAccountName();
    $roles = array();
    $roles = \Drupal::currentUser()->getRoles();
    if(count($roles) > 0){ $roles = implode(",", $roles); }
    $form['#attached']['drupalSettings']['arche_core_gui']['users']['roles'] = $roles;
    
    $current_path = \Drupal::service('path.current')->getPath();
    
    return $form;
}

function arche_core_gui_theme($existing, $type, $theme, $path)
{
    return [
        'arche-detail' => [
            'variables' => ['data' => NULL, 'identifier' => NULL],
        ],
        'arche-detail-empty' => [
            'variables' => ['data' => NULL, 'identifier' => NULL],
        ],
         'arche-discover' => [
            'variables' => ['data' => NULL, 'vcrUrl' => NULL],
        ],
        'dissemination-3d-viewer' => [
            'variables' => ['data' => NULL, 'basic' => NULL],
        ],
        'dissemination-pdf-viewer' => [
            'variables' => ['data' => NULL, 'basic' => NULL],
        ],
        'dissemination-iiif-viewer' => [
            'variables' => ['data' => NULL, 'basic' => NULL],
        ],
        'dissemination-audio-viewer' => [
            'variables' => ['data' => NULL, 'basic' => NULL],
        ],
        'helper-lng-switcher' => [
            'variables' => ['language' => NULL]
        ],
        'imprint' => [
            'variables' => ['content' => NULL]
        ],        
    ];
}



