rest:
  headers:
    metadataReadMode: X-METADATA-READ-MODE
    metadataParentProperty: X-PARENT-PROPERTY
    metadataWriteMode: X-METADATA-WRITE-MODE
    transactionId: X-TRANSACTION-ID
    withReferences: X-WITH-REFERENCES
    resourceProperties: X-RESOURCE-PROPERTIES
    relativesProperties: X-RELATIVES-PROPERTIES
  handlers:
    methods:
      get:
      - type: function
        function: \acdhOeaw\arche\openaire\Handlers::onGet
      getMetadata:
      - type: function
        function: \acdhOeaw\arche\openaire\Handlers::onGetMetadata
  urlBase: http://127.0.0.1
  pathBase: /api/
schema:
  id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
  parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
  label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
  delete: delete://delete
  searchMatch: search://match
  searchOrder: search://order
  searchOrderValue: search://orderValue
  searchFts: search://fts
  searchFtsProperty: search://ftsProperty
  searchFtsQuery: search://ftsQuery
  searchCount: search://count
  searchWeight: search://weight
  binarySize: https://vocabs.acdh.oeaw.ac.at/schema#hasRawBinarySize
  fileName: https://vocabs.acdh.oeaw.ac.at/schema#hasFilename
  mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
  hash: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
  modificationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasUpdatedDate
  modificationUser: https://vocabs.acdh.oeaw.ac.at/schema#hasUpdatedRole
  binaryModificationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasBinaryUpdatedDate
  binaryModificationUser: https://vocabs.acdh.oeaw.ac.at/schema#hasBinaryUpdatedRole
  creationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
  creationUser: https://vocabs.acdh.oeaw.ac.at/schema#createdBy
  pid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
  binarySizeCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
  hosting: https://vocabs.acdh.oeaw.ac.at/schema#hasHosting
  accessRole: https://vocabs.acdh.oeaw.ac.at/schema#hasRestrictionRole
  accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
  accessRestrictionAgg: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestrictionSummary
  license: https://vocabs.acdh.oeaw.ac.at/schema#hasLicense
  licenseAgg: https://vocabs.acdh.oeaw.ac.at/schema#hasLicenseSummary
  countCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems
  isNewVersionOf: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
  cmdiPid: https://vocabs.acdh.oeaw.ac.at/schema#hasMetadataPid
  biblatex: https://vocabs.acdh.oeaw.ac.at/schema#hasCustomCitation
  titleImage: https://vocabs.acdh.oeaw.ac.at/schema#isTitleImageOf
  latitude: https://vocabs.acdh.oeaw.ac.at/schema#hasLatitude
  longitude: https://vocabs.acdh.oeaw.ac.at/schema#hasLongitude
  wkt: https://vocabs.acdh.oeaw.ac.at/schema#hasWKT
  classes:
    agent: https://vocabs.acdh.oeaw.ac.at/schema#Agent
    binaryContent: https://vocabs.acdh.oeaw.ac.at/schema#BinaryContent
    collection: https://vocabs.acdh.oeaw.ac.at/schema#Collection
    image: https://vocabs.acdh.oeaw.ac.at/schema#Image
    metadata: https://vocabs.acdh.oeaw.ac.at/schema#Metadata
    organisation: https://vocabs.acdh.oeaw.ac.at/schema#Organisation
    person: https://vocabs.acdh.oeaw.ac.at/schema#Person
    place: https://vocabs.acdh.oeaw.ac.at/schema#Place
    project: https://vocabs.acdh.oeaw.ac.at/schema#Project
    publication: https://vocabs.acdh.oeaw.ac.at/schema#Publication
    repoObject: https://vocabs.acdh.oeaw.ac.at/schema#RepoObject
    resource: https://vocabs.acdh.oeaw.ac.at/schema#Resource
    sharedObject: https://vocabs.acdh.oeaw.ac.at/schema#AgentOrPlaceOrPublication
    topCollection: https://vocabs.acdh.oeaw.ac.at/schema#TopCollection
  namespaces:
    id: https://id.acdh.oeaw.ac.at/
    cmdi: https://id.acdh.oeaw.ac.at/cmdi/
    ebucore: http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#
    fedora: http://fedora.info/definitions/v4/repository#
    ontology: https://vocabs.acdh.oeaw.ac.at/schema#
    premis: http://www.loc.gov/premis/rdf/v1#
    rdfs: http://www.w3.org/1999/02/22-rdf-syntax-ns#
    vid: https://id.acdh.oeaw.ac.at/vid/
  dissService:
    class: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationService
    location: https://vocabs.acdh.oeaw.ac.at/schema#serviceLocation
    returnFormat: https://vocabs.acdh.oeaw.ac.at/schema#hasReturnType
    matchProperty: https://vocabs.acdh.oeaw.ac.at/schema#matchesProp
    matchValue: https://vocabs.acdh.oeaw.ac.at/schema#matchesValue
    matchRequired: https://vocabs.acdh.oeaw.ac.at/schema#isRequired
    revProxy: https://vocabs.acdh.oeaw.ac.at/schema#serviceRevProxy
    parameterClass: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter
    parameterDefaultValue: https://vocabs.acdh.oeaw.ac.at/schema#hasDefaultValue
    parameterRdfProperty: https://vocabs.acdh.oeaw.ac.at/schema#usesRdfProperty
    hasService: https://vocabs.acdh.oeaw.ac.at/schema#hasDissService
    parent: https://vocabs.acdh.oeaw.ac.at/schema#relation
  ingest:
    location: https://vocabs.acdh.oeaw.ac.at/schema#hasLocationPath
    containerToUriPrefix: acdhContainer://
    defaultBinaryClass: https://vocabs.acdh.oeaw.ac.at/schema#Resource
    defaultCollectionClass: https://vocabs.acdh.oeaw.ac.at/schema#Collection
  ontology:
    order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
    recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
    langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
    vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
    dateStart: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedStartDate
    dateEnd: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedEndDate
    url: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
    version: https://vocabs.acdh.oeaw.ac.at/schema#hasVersion
    info: https://vocabs.acdh.oeaw.ac.at/schema#hasVersionInfo
    description: https://vocabs.acdh.oeaw.ac.at/schema#hasDescription
  drupal:
    vocabsNamespace: https://vocabs.acdh.oeaw.ac.at/schema#
    uuidNamespace: https://id.acdh.oeaw.ac.at/uuid/
    idNamespace: https://id.acdh.oeaw.ac.at/
    epicResolver: https://hdl.handle.net/
    geonamesUrl: https://www.geonames.org/
    dnbUrl: http://d-nb.info/
    viafUrl: http://viaf.org/
    orcidUrl: https://orcid.org/
    pelagiosUrl: https://pleiades.stoa.org/
    gazetteerUrl: https://gazetteer.dainst.org/
    doiUrl: https://doi.org/
openaire:
  url: https://analytics.openaire.eu/piwik.php
  id: 602
  authToken: ""
  trackIp: false
  trackUserAgent: true
  pidQuery: |
    SELECT m1.value
    FROM
        (SELECT id FROM get_relatives(?, ?, 0, -99999, false, false) t ORDER BY n LIMIT 1) i
        JOIN metadata m1 USING (id)
        JOIN metadata m2 USING (id)
    WHERE m1.property = ? AND m2.property = ? AND m2.value = ?
  pidQueryParam:
  - '{id}'
  - https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
  - https://vocabs.acdh.oeaw.ac.at/schema#hasPid
  - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
  - https://vocabs.acdh.oeaw.ac.at/schema#TopCollection
dbConn:
  guest: 'pgsql: host=127.0.0.1 port=5432 user=gui dbname=www-data'
dbConnStr:
  guest: 'pgsql: host=127.0.0.1 port=5432 user=gui dbname=www-data'
clarinVcrUrl: https://collections.clarin.eu/submit/extensional
smartSearch:
  prefLang: en
  property:
    label: Search match in
    weights:
      https://vocabs.acdh.oeaw.ac.at/schema#hasTitle: 100
      https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier: 50
      https://vocabs.acdh.oeaw.ac.at/schema#hasDescription: 10
  facets:
  - label: Type
    property: http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    weights:
      https://vocabs.acdh.oeaw.ac.at/schema#TopCollection: 500
      https://vocabs.acdh.oeaw.ac.at/schema#Collection: 49
  - label: License
    property: https://vocabs.acdh.oeaw.ac.at/schema#hasLicense
    type: object
    weights:
      48908: 1.1
      48916: 1.1
      48534: 1
      48907: 1
      48903: 1
      48904: 1
      48905: 1
      48910: 0.5
  - label: Access restriction
    property: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    type: object
    weights:
      48508: 1.1
      48513: 1
      48519: 0.5
  - label: Related discipline
    property: https://vocabs.acdh.oeaw.ac.at/schema#hasRelatedDiscipline
    type: object
    weights: []
  - label: Category
    property: https://vocabs.acdh.oeaw.ac.at/schema#hasCategory
    type: object
    weights: []
  dateFacets:
    content:
      label: Temporal coverage
      bins: 5
      start:
      - https://vocabs.acdh.oeaw.ac.at/schema#hasCoverageStartDate
      - https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedStartDateOriginal
      end:
      - https://vocabs.acdh.oeaw.ac.at/schema#hasCoverageEndDate
      - https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedEndDateOriginal
    archive:
      label: Available since
      bins: 5
      start: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
      end: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
  namedEntities:
    defaultWeight: 1
    weights:
      https://vocabs.acdh.oeaw.ac.at/schema#hasAuthor: 10
      https://vocabs.acdh.oeaw.ac.at/schema#hasRelatedDiscipline: 5
      https://vocabs.acdh.oeaw.ac.at/schema#hasActor: 1
    classes:
    - https://vocabs.acdh.oeaw.ac.at/schema#Organisation
    - https://vocabs.acdh.oeaw.ac.at/schema#Person
    - https://vocabs.acdh.oeaw.ac.at/schema#Place
    - https://vocabs.acdh.oeaw.ac.at/schema#Project
    - https://vocabs.acdh.oeaw.ac.at/schema#Publication
    - http://www.w3.org/2004/02/skos/core#Concept
metadataManagment:
  nonRelationProperties:
  - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
doorkeeper:
  epicPid:
    pswd: ~
oai:
  info:
    baseUrl: http://127.0.0.1/oaipmh/
  search:
    repoBaseUrl: http://127.0.0.1/api/
resolver:
  repositories:
    self:
      baseUrl: http://127.0.0.1/api/
openrefine:
  baseUrl: http://127.0.0.1/openrefine/
  viewUrl: http://127.0.0.1/browser/oeaw_detail/{{id}}
